#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,20
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,20
env = WLR_RENDERER,vulkan
env = LIBVA_DRIVER_NAME,iHD
env = WLR_DRM_NO_ATOMIC,1

