-- Generated by matugen. Do not edit.
return {
	base00 = "{{colors.background.default.hex}}", --background
	base01 = "{{colors.surface_container_lowest.default.hex}}", --line numbers
	base02 = "{{colors.surface_container_low.default.hex}}", --current line
	base03 = "{{colors.outline.default.hex}}", --comments

	base04 = "{{colors.primary_fixed.default.hex}}",
	base05 = "{{colors.primary_fixed.default.hex}}", --normal text
	base06 = "{{colors.primary_fixed.default.hex}}",
	base07 = "{{colors.primary_fixed.default.hex}}",

	base08 = "{{colors.primary.default.hex}}", --references
	base09 = "{{colors.primary.default.hex}}", --variables

	base0A = "{{colors.primary.default.hex}}",
	base0B = "{{colors.secondary.default.hex}}", --string text

	base0C = "{{colors.tertiary.default.hex}}", --blocks
	base0D = "{{colors.primary.default.hex}}", --function calls
	base0E = "{{colors.inverse_primary.default.hex}}", --if, for, while statements
	base0F = "{{colors.tertiary_fixed.default.hex}}", --punctuation
}
